//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domaci1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Fakultet1Entities : DbContext
    {
        public Fakultet1Entities()
            : base("name=Fakultet1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ispit> Ispits { get; set; }
        public virtual DbSet<Predmet> Predmets { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
